# Generated by Django 5.2.6 on 2025-09-09 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_recognition', '0002_flashcard_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='label',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
