# Generated by Django 5.2.6 on 2025-09-13 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_recognition', '0003_alter_flashcard_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='image',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='label',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='flashcards/'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='palabra',
            field=models.CharField(default='pendiente', max_length=100),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='traduccion',
            field=models.CharField(default='pendiente', max_length=100),
        ),
    ]
