# Generated by Django 5.2.6 on 2025-09-13 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_recognition', '0004_remove_flashcard_created_at_remove_flashcard_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='palabra',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='traduccion',
            field=models.CharField(max_length=100),
        ),
    ]
