# Generated by Django 5.2.6 on 2025-09-13 04:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_recognition', '0005_alter_flashcard_palabra_alter_flashcard_traduccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='interval',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='next_review',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='repetitions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='traduccion',
            field=models.CharField(max_length=200),
        ),
    ]
