# Generated by Django 5.2.6 on 2025-09-13 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_recognition', '0006_flashcard_interval_flashcard_next_review_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='repetitions',
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='traduccion',
            field=models.CharField(max_length=100),
        ),
    ]
